# Generated by Django 5.0.6 on 2026-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(default='stethoscope', help_text='Icon keyword used by the frontend (e.g. heart, bone, brain).', max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('services', models.TextField(blank=True, help_text='One service per line.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
