# Generated by Django 5.0.6 on 2026-07-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('specialization', models.CharField(max_length=150)),
                ('qualifications', models.CharField(help_text='e.g. MBBS, MD (Cardiology)', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True, help_text='Optional profile photo URL.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('available_days', models.CharField(default='Monday - Friday', help_text="e.g. 'Mon, Wed, Fri' or 'Monday - Friday'", max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='departments.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
